apiVersion: v1
kind: Service
metadata:
  name: {{ include "kache-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kache-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kache-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- with .Values.service.appProtocol }}
      appProtocol: {{ . | quote }}
      {{- end }}
